### ISSUE TITLE
Exe crashing

### ISSUE THREAD

**Issue by AndrisBorbas** [Apophenic/iTunes-Skins-Windows#1]
So i dont actually know how to use it, but if i run the exe it just crashes with this: 
Beginning Extraction Operation...

Unhandled Exception: System.ComponentModel.Win32Exception: The parameter is incorrect
   at Vestris.ResourceLib.ResourceInfo.Load(String filename)
   at iTunesSkinTools.Program.extractResources()
   at iTunesSkinTools.Program.Main(String[] args)

**Comment by AndrisBorbas** [comment]
I think its an issue with the 64 bit executable.

**Comment by AndyBlak1** [comment]
Hi, I am having this issue as well, and I would also like to know about a solution, please.

**Comment by AndreThompson-Atlow** [comment]
Any chance of it being fixed in 2021? lol
